# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in 'proguard-android-optimize.txt' defined by the Android Gradle plugin.

# ─── Flutter ────────────────────────────────────────────────────────────────
-keep class io.flutter.** { *; }
-keep class io.flutter.embedding.** { *; }
-dontwarn io.flutter.embedding.**

# ─── Kotlin / Coroutines ────────────────────────────────────────────────────
-keep class kotlin.** { *; }
-keep class kotlinx.coroutines.** { *; }
-dontwarn kotlinx.coroutines.**
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}

# ─── Supabase / Ktor / Realtime ─────────────────────────────────────────────
-keep class io.github.jan.supabase.** { *; }
-keep class io.ktor.** { *; }
-dontwarn io.ktor.**
-keep class org.postgresql.** { *; }

# ─── OkHttp / Retrofit (used by Supabase/Ktor internally) ───────────────────
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep class okio.** { *; }

# ─── Google Sign-In / Auth ───────────────────────────────────────────────────
-keep class com.google.android.gms.auth.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**

# ─── Firebase Messaging (FCM) ────────────────────────────────────────────────
-keep class com.google.firebase.** { *; }
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.**
-keep class io.flutter.plugins.firebase.** { *; }

# ─── Firebase / Google Sign-In (prevent signin failure on some devices) ───────
-keep public class com.google.firebase.** { *; }
-keep class com.google.android.gms.internal.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.auth.api.** { *; }

# ─── Razorpay ────────────────────────────────────────────────────────────────
-keep class com.razorpay.** { *; }
-dontwarn com.razorpay.**
-keep class proguard.annotation.Keep
-keep class proguard.annotation.KeepClassMembers
-keepattributes *Annotation*

# ─── JSON Serialization (Gson/kotlinx.serialization) ────────────────────────
-keepattributes Signature
-keepattributes EnclosingMethod
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.** { *; }
-dontwarn com.google.gson.**

# ─── Supabase Auth / JWT ─────────────────────────────────────────────────────
-keep class io.jsonwebtoken.** { *; }
-dontwarn io.jsonwebtoken.**

# ─── URL Launcher ────────────────────────────────────────────────────────────
-keep class io.flutter.plugins.urllauncher.** { *; }

# ─── Flutter Local Notifications ─────────────────────────────────────────────
-keep class com.dexterous.** { *; }

# ─── Reflection (required by many SDKs) ──────────────────────────────────────
-keepattributes *Annotation*
-keepattributes InnerClasses
-keepattributes EnclosingMethod
-keepattributes Exceptions

# ─── Auto-generated by Gradle (missing_rules.txt) ────────────────────────────
-dontwarn javax.xml.stream.XMLStreamException
-dontwarn org.apache.tika.**
