-- Create Reviews Table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  item_id bigint not null, -- Stores test_id or resource_id
  item_type text not null check (item_type in ('test', 'resource')),
  rating numeric not null check (rating >= 1 and rating <= 5),
  review_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Ensure one review per item per user
  unique(user_id, item_id, item_type)
);

-- Enable RLS
alter table public.reviews enable row level security;

-- Policies
create policy "Public reviews are viewable by everyone."
  on public.reviews for select
  using ( true );

create policy "Users can insert their own reviews."
  on public.reviews for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own reviews."
  on public.reviews for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own reviews."
  on public.reviews for delete
  using ( auth.uid() = user_id );

-- Create Index for faster lookups
create index if not exists reviews_item_lookup_idx on public.reviews (item_id, item_type);
