import 'dart:io';
import 'package:path/path.dart' as p;

// ─── helpers ──────────────────────────────────────────────────────────────────

/// Strip a known suffix from the END of a string (safe – no mid-path mangling).
String _stripSuffix(String s, String suffix) {
  if (s.endsWith(suffix)) {
    return s.substring(0, s.length - suffix.length);
  }
  return s;
}

/// Resolve a generated path (.g.dart / .freezed.dart) back to its source file.
String _toSourcePath(String path) {
  if (path.endsWith('.g.dart')) {
    return '${_stripSuffix(path, '.g.dart')}.dart';
  }
  if (path.endsWith('.freezed.dart')) {
    return '${_stripSuffix(path, '.freezed.dart')}.dart';
  }
  return path;
}

// ─────────────────────────────────────────────────────────────────────────────

void main() {
  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    print('Error: Run this script from the root of the krushi_kalp Flutter project.');
    return;
  }

  // ── 1. Gather all Dart files ──────────────────────────────────────────────
  final allFiles = libDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .toList();

  // Source files = no generated files.
  final sourceFiles = allFiles
      .where((f) => !f.path.endsWith('.g.dart') && !f.path.endsWith('.freezed.dart'))
      .toList();

  // Canonical (normalised absolute) path → file.
  final Set<String> allSourcePaths =
      sourceFiles.map((f) => p.normalize(f.absolute.path)).toSet();

  // importedByMap[X] = set of source files that import X.
  final Map<String, Set<String>> importedByMap = {
    for (var path in allSourcePaths) path: {},
  };

  // ── 2. Build the import graph ─────────────────────────────────────────────
  final importRegex = RegExp(r"^(?:import|export)\s+'([^']+)'", multiLine: true);

  // Read every dart file (including generated) for the import graph, but only
  // add source files as "nodes".
  final Map<String, String> fileContents = {
    for (var f in allFiles) p.normalize(f.absolute.path): f.readAsStringSync(),
  };

  // External package prefixes we don't want to resolve locally.
  const skipPrefixes = [
    'dart:',
    'package:flutter/',
    'package:flutter_test/',
    'package:supabase_flutter/',
    'package:isar/',
    'package:isar_community/',
    'package:flutter_riverpod/',
    'package:riverpod_annotation/',
    'package:freezed_annotation/',
    'package:path/',
    'package:path_provider/',
    'package:dio/',
    'package:go_router/',
  ];

  for (var file in sourceFiles) {
    final path = p.normalize(file.absolute.path);
    final content = fileContents[path]!;
    final currentDir = p.dirname(path);

    for (final match in importRegex.allMatches(content)) {
      final target = match.group(1)!;
      if (skipPrefixes.any((px) => target.startsWith(px))) continue;

      String? rawTarget;
      if (target.startsWith('package:krushi_kalp/')) {
        final rest = target.substring('package:krushi_kalp/'.length);
        rawTarget = p.normalize(p.join(libDir.absolute.path, rest));
      } else if (!target.startsWith('package:')) {
        rawTarget = p.normalize(p.join(currentDir, target));
      }

      if (rawTarget == null) continue;

      // Map generated files back to their source counterpart.
      final sourcePath = _toSourcePath(rawTarget);

      if (allSourcePaths.contains(sourcePath)) {
        importedByMap[sourcePath]!.add(path);
      }
    }
  }

  // ── 3. Report unused FILES ────────────────────────────────────────────────
  // entry-points that should never be flagged as "unused"
  final entryPoints = {
    p.normalize(p.join(libDir.absolute.path, 'main.dart')),
  };

  final unusedFiles = <String>[];
  for (final path in allSourcePaths) {
    if (entryPoints.contains(path)) continue;
    if (importedByMap[path]!.isEmpty) {
      unusedFiles.add(p.relative(path, from: Directory.current.absolute.path));
    }
  }

  unusedFiles.sort();
  print('=== UNUSED FILES ===');
  for (final f in unusedFiles) print(' - $f');
  print('Total unused files: ${unusedFiles.length}\n');

  // ── 4. Report potentially unused public DECLARATIONS ─────────────────────
  // These classes/mixins/enums are generated BY codegen, not referenced by name.
  // Treat them as always-used to avoid false positives.
  final generatedByCodegen = RegExp(
    r'^(?:'
    r'.*Notifier'           // Riverpod notifiers (AuthNotifier, CartNotifier…)
    r'|.*State'             // Freezed state classes
    r'|.*CopyWith'          // Freezed CopyWith helpers
    r'|\$.*Impl'            // Freezed impls
    r')$',
  );

  final classRegex = RegExp(r'\b(?:abstract\s+)?(?:class|mixin|enum)\s+([A-Z][A-Za-z0-9_]*)');
  final providerRegex = RegExp(r'\b(?:final|const|var)\s+([a-zA-Z0-9_]+Provider)\b');

  print('=== POTENTIALLY UNUSED DECLARATIONS ===');
  int unusedDecls = 0;

  for (final file in sourceFiles) {
    final path = p.normalize(file.absolute.path);
    final relPath = p.relative(path, from: Directory.current.absolute.path);

    // Skip files that are themselves unused (already reported above).
    if (unusedFiles.contains(relPath)) continue;
    if (entryPoints.contains(path)) continue;

    final content = fileContents[path]!;
    final decls = <String>{};

    for (final m in classRegex.allMatches(content)) {
      final name = m.group(1)!;
      // Skip private and codegen-managed classes.
      if (!name.startsWith('_') && !generatedByCodegen.hasMatch(name)) {
        decls.add(name);
      }
    }

    for (final m in providerRegex.allMatches(content)) {
      final name = m.group(1)!;
      if (!name.startsWith('_')) decls.add(name);
    }

    for (final decl in decls) {
      bool isUsed = false;

      // Check every file (including generated ones) for a reference to `decl`.
      for (final otherPath in fileContents.keys) {
        if (otherPath == path) continue; // skip self

        // Skip the generated counterpart of *this* file (e.g. auth_notifier.g.dart
        // for auth_notifier.dart) – it will always reference the class, but that
        // doesn't count as "external" usage.
        final thisBase = _stripSuffix(
            _stripSuffix(p.basename(path), '.dart'), '');
        final otherBase = p.basename(otherPath);
        if (otherBase == '$thisBase.g.dart' ||
            otherBase == '$thisBase.freezed.dart') continue;

        if (fileContents[otherPath]!.contains(RegExp('\\b$decl\\b'))) {
          isUsed = true;
          break;
        }
      }

      if (!isUsed) {
        print(' - $decl  →  $relPath');
        unusedDecls++;
      }
    }
  }

  print('Total potentially unused declarations: $unusedDecls');
}
