import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../../domain/models/question.dart';
import '../../utils/crashlytics_service.dart';

class PdfService {
  // Maintaining a public constructor for existing usage
  PdfService();

  static final PdfService instance = PdfService();

  /// Main method to generate a professional exam result PDF.
  Future<File> generateExamResultPdf({
    required String testId,
    required String testTitle,
    required double score,
    required double totalMarks,
    required int correctAnswers,
    required int wrongAnswers,
    required int skippedAnswers,
    required String userId,
    required String userName,
    List<Question>? questions,
    Map<int, int>? selectedAnswers,
    String languageCode = 'en',
  }) async {
    final pdf = pw.Document(
      author: 'Krushi Kalp',
      title: 'Exam Result - $testTitle',
      subject: 'Mock Test Result Analysis',
      keywords: 'krushi kalp, agriculture, mock test, result',
    );

    // Load Fonts based on language
    final primaryFont = await _loadFont(languageCode);
    final fallbackFont = await _loadFont('gu', forceGujarati: true);




    // Using MultiPage with standard A4 to bypass platform height limits
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(0),
        theme: pw.ThemeData.withFont(
          base: primaryFont,
          bold: primaryFont,
          italic: primaryFont,
        ).copyWith(
          defaultTextStyle: pw.TextStyle(
            fontFallback: [primaryFont, fallbackFont],
          ),
        ),
        footer: (pw.Context context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          padding: const pw.EdgeInsets.only(right: 30, bottom: 20),
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(color: PdfColors.grey500, fontSize: 10),
          ),
        ),
        build: (pw.Context context) => [
          _buildPremiumHeader(testTitle, score, totalMarks, correctAnswers, wrongAnswers, skippedAnswers),
          if (questions != null) ...[
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(horizontal: 30, vertical: 20),
              child: pw.Text(
                'Detailed Analysis',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.black,
                ),
              ),
            ),
            ...questions.asMap().entries.map((entry) {
              final index = entry.key;
              final q = entry.value;
              final selectedIdx = selectedAnswers?[index];
              return _buildAnalysisCard(
                index + 1,
                q,
                selectedIdx,
              );
            }),
          ],
          pw.SizedBox(height: 30),
          pw.Center(
             child: pw.Text(
              'Generated by Krushi Kalp App',
              style: pw.TextStyle(color: PdfColors.grey500, fontSize: 10, fontStyle: pw.FontStyle.italic),
            ),
          ),
          pw.SizedBox(height: 20),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File("${dir.path}/result_$testId.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  pw.Widget _buildPremiumHeader(
    String title,
    double score,
    double totalMarks,
    int correct,
    int wrong,
    int skipped,
  ) {
    final double percentage = (score / totalMarks) * 100;
    final bool isPassed = percentage >= 35; // Standard passing mark
    final PdfColor brandBlue = PdfColor.fromInt(0xFF3399FF);
    final PdfColor statRed = PdfColor.fromInt(0xFFF44336);

    return pw.Column(
      children: [
        // Top Brand Bar
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 30),
          color: PdfColors.grey100,
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('KRUSHI KALP', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.grey700)),
              pw.Text('${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
            ],
          ),
        ),
        // Total Score Card (Matches TestResultScreen)
        pw.Container(
          width: double.infinity,
          margin: const pw.EdgeInsets.all(30),
          padding: const pw.EdgeInsets.all(32),
          decoration: pw.BoxDecoration(
            color: brandBlue,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(20)),
          ),
          child: pw.Column(
            children: [
              pw.Text(
                'TOTAL SCORE',
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontWeight: pw.FontWeight.bold,
                  letterSpacing: 1.5,
                  fontSize: 12,
                ),
              ),
              pw.SizedBox(height: 16),
              // Icon (Directly on blue background for clarity)
              pw.Container(
                width: 40,
                height: 40,
                child: pw.CustomPaint(
                  painter: (PdfGraphics canvas, PdfPoint size) {
                    canvas.setStrokeColor(PdfColors.white);
                    canvas.setLineWidth(4); // Increased for better visibility
                    if (isPassed) {
                      // Trophy-like shape
                      canvas.drawEllipse(size.x / 2, size.y * 0.7, 10, 8);
                      canvas.moveTo(size.x / 2, size.y * 0.4);
                      canvas.lineTo(size.x / 2, size.y * 0.2);
                      canvas.moveTo(size.x / 2 - 8, size.y * 0.2);
                      canvas.lineTo(size.x / 2 + 8, size.y * 0.2);
                    } else {
                      // Sad face
                      canvas.drawEllipse(size.x / 2, size.y / 2, 12, 12);
                      canvas.moveTo(size.x / 2 - 4, size.y / 2 + 3);
                      canvas.drawEllipse(size.x / 2 - 4, size.y / 2 + 3, 1, 1);
                      canvas.moveTo(size.x / 2 + 4, size.y / 2 + 3);
                      canvas.drawEllipse(size.x / 2 + 4, size.y / 2 + 3, 1, 1);
                      canvas.moveTo(size.x / 2 - 5, size.y / 2 - 3);
                      canvas.setLineCap(PdfLineCap.round);
                      canvas.curveTo(size.x / 2 - 5, size.y / 2 - 3, size.x/2, size.y/2, size.x/2+5, size.y/2-3);
                    }
                    canvas.strokePath();
                  },
                ),
              ),
              pw.SizedBox(height: 16),
              pw.Text(
                '${percentage.toStringAsFixed(1)}%',
                style: pw.TextStyle(
                  fontSize: 48,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.white,
                ),
              ),
              pw.Text(
                'OUT OF ${totalMarks.toInt()}',
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontWeight: pw.FontWeight.bold,
                  letterSpacing: 2,
                  fontSize: 10,
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                isPassed
                    ? 'Test Completed Successfully\nYou have achieved the passing score for the $title.'
                    : 'Test Not Cleared\nYou did not achieve the required passing score for the $title.',
                textAlign: pw.TextAlign.center,
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 14,
                  lineSpacing: 1.4,
                ),
              ),
            ],
          ),
        ),
        // Stat Cards Row
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 30),
          child: pw.Row(
            children: [
              pw.Expanded(
                child: _buildStatCard('RIGHT', '$correct', brandBlue),
              ),
              pw.SizedBox(width: 20),
              pw.Expanded(
                child: _buildStatCard('WRONG', '$wrong', statRed),
              ),
              pw.SizedBox(width: 20),
              pw.Expanded(
                child: _buildStatCard('SKIPPED', '$skipped', PdfColors.grey700),
              ),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _buildStatCard(String label, String value, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 20),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(15)),
        border: pw.Border.all(color: PdfColors.grey200),
      ),
      child: pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey600,
              letterSpacing: 1.2,
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildAnalysisCard(
    int number,
    Question q,
    int? selectedIdx,
  ) {
    final PdfColor correctGreen = PdfColor.fromInt(0xFF4CAF50);
    final PdfColor correctLight = PdfColor.fromInt(0xFFE8F5E9);
    final PdfColor errorRed = PdfColor.fromInt(0xFFF44336);
    final PdfColor errorLight = PdfColor.fromInt(0xFFFFEBEE);


    final isSkipped = selectedIdx == null;

    return pw.Container(
      margin: const pw.EdgeInsets.symmetric(horizontal: 30, vertical: 8),
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        border: pw.Border.all(color: PdfColors.grey200, width: 0.8),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(16)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          // Card Header: Grey circle + "Question N"
          pw.Row(
            children: [
              pw.Container(
                width: 22,
                height: 22,
                decoration: const pw.BoxDecoration(
                  color: PdfColors.grey400,
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Container(
                    width: 10,
                    height: 10,
                    child: pw.CustomPaint(
                      painter: (PdfGraphics canvas, PdfPoint size) {
                        canvas.setStrokeColor(PdfColors.white);
                        canvas.setLineWidth(2);
                        canvas.moveTo(2, 5);
                        canvas.lineTo(8, 5);
                        canvas.strokePath();
                      },
                    ),
                  ),
                ),
              ),
              pw.SizedBox(width: 10),
              pw.Text(
                'Question $number',
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey600,
                  fontSize: 12,
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 12),
          // Question Text
          pw.Text(
            q.text,
            style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 14,
              color: PdfColors.black,
            ),
          ),
          pw.SizedBox(height: 16),
          // Options
          ...List.generate(q.options.length, (optIndex) {
            final isSelected = selectedIdx == optIndex;
            final isRealAnswer = q.options[optIndex].trim().toLowerCase() ==
                q.correctAnswer.trim().toLowerCase();

            PdfColor borderColor = PdfColors.grey200;
            PdfColor bgColor = PdfColors.white;

            if (isRealAnswer) {
              borderColor = correctGreen;
              bgColor = correctLight;
            } else if (isSelected && !isRealAnswer) {
              borderColor = errorRed;
              bgColor = errorLight;
            }

            return pw.Container(
              margin: const pw.EdgeInsets.only(bottom: 10),
              padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 12),
              decoration: pw.BoxDecoration(
                color: bgColor,
                border: pw.Border.all(color: borderColor, width: 1.2),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Expanded(
                    child: pw.Text(
                      q.options[optIndex],
                      style: pw.TextStyle(
                        color: PdfColors.black,
                        fontSize: 12,
                        fontWeight: (isSelected || isRealAnswer) ? pw.FontWeight.bold : pw.FontWeight.normal,
                      ),
                    ),
                  ),
                  if (isRealAnswer || (isSelected && !isRealAnswer))
                    _buildSelectionIndicator(isRealAnswer, correctGreen, errorRed),
                ],
              ),
            );
          }),
          if (isSkipped)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 8),
              child: pw.Text(
                'You skipped this question',
                style: pw.TextStyle(
                  color: PdfColors.blueGrey400,
                  fontSize: 10,
                  fontStyle: pw.FontStyle.italic,
                ),
              ),
            ),
        ],
      ),
    );
  }



  pw.Widget _buildSelectionIndicator(bool isCorrect, PdfColor darkG, PdfColor darkR) {
    return pw.Container(
      width: 18,
      height: 18,
      decoration: pw.BoxDecoration(
        color: isCorrect ? darkG : darkR,
        shape: pw.BoxShape.circle,
      ),
      child: pw.Center(
        child: pw.Container(
          width: 10,
          height: 10,
          child: pw.CustomPaint(
            painter: (PdfGraphics canvas, PdfPoint size) {
              canvas.setStrokeColor(PdfColors.white);
              canvas.setLineWidth(1.8);
              if (isCorrect) {
                canvas.moveTo(2, 5);
                canvas.lineTo(4, 7);
                canvas.lineTo(8, 2);
              } else {
                canvas.moveTo(2, 2);
                canvas.lineTo(8, 8);
                canvas.moveTo(2, 8);
                canvas.lineTo(8, 2);
              }
              canvas.strokePath();
            },
          ),
        ),
      ),
    );
  }

  /// Loads the required font based on language.
  Future<pw.Font> _loadFont(String languageCode,
      {bool forceGujarati = false}) async {
    // For English, use standard PDF fonts for better rendering and performance
    if (languageCode == 'en' && !forceGujarati) {
      return pw.Font.helvetica();
    }

    try {
      // 1. Try Bundled Asset (Fastest & Offline)
      try {
        final fontData =
            await rootBundle.load("assets/fonts/NotoSansGujarati-Regular.ttf");
        return pw.Font.ttf(fontData);
      } catch (e, stack) {
        // Log if asset loading fails, will fall back to cache/download
        CrashlyticsService.instance.recordError(e, stack,
            reason: 'PdfService: Bundled font asset load failed');
      }

      final dir = await getApplicationDocumentsDirectory();
      final file = File("${dir.path}/NotoSansGujarati.ttf");

      // 2. Use Cache if available
      if (await file.exists()) {
        try {
          return pw.Font.ttf(
              await file.readAsBytes().then((b) => b.buffer.asByteData()));
        } catch (e, stack) {
          CrashlyticsService.instance
              .recordError(e, stack, reason: 'pdf_service');
          await file.delete();
        }
      }

      // 3. Download from JSDelivr (Reliable Source)
      final url = Uri.parse(
          "https://cdn.jsdelivr.net/npm/@expo-google-fonts/noto-sans-gujarati@0.2.3/NotoSansGujarati_400Regular.ttf");

      final client = HttpClient()
        ..badCertificateCallback = (cert, host, port) => true;

      final request = await client.getUrl(url);
      final response = await request.close();

      if (response.statusCode == 200) {
        final bytes = await condenseStream(response);
        await file.writeAsBytes(bytes);
        return pw.Font.ttf(bytes.buffer.asByteData());
      }
    } catch (e, stack) {
      CrashlyticsService.instance.recordError(e, stack,
          reason: 'PdfService: All font loading strategies failed');
    }
    // Fallback
    return pw.Font.helvetica();
  }

  Future<Uint8List> condenseStream(Stream<List<int>> stream) async {
    final List<int> allBytes = [];
    await for (final List<int> chunk in stream) {
      allBytes.addAll(chunk);
    }
    return Uint8List.fromList(allBytes);
  }





  String getSecurePassword(String userId, String testTitle) {
    // Deterministic password based on user and test
    return "${userId.substring(0, 4)}@${testTitle.length}";
  }
}
