import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../../domain/models/question.dart';


class PdfService {
  // Maintaining a public constructor for existing usage
  PdfService();

  static final PdfService instance = PdfService();

  /// Main method to generate a professional exam result PDF.
  Future<File> generateExamResultPdf({
    required String testId,
    required String testTitle,
    required double score,
    required double totalMarks,
    required int correctAnswers,
    required int wrongAnswers,
    required int skippedAnswers,
    required String userId,
    required String userName,
    List<Question>? questions,
    Map<int, int>? selectedAnswers,
    String languageCode = 'en',
  }) async {
    final pdf = pw.Document(
      author: 'Krushi Kalp',
      title: 'Exam Result - $testTitle',
      subject: 'Mock Test Result Analysis',
      keywords: 'krushi kalp, agriculture, mock test, result',
    );

    // Load Fonts - Force Unicode for everything to avoid path/height errors
    final primaryFont = await _loadFont(languageCode);
    final fallbackFont = await _loadFont('gu', forceGujarati: true);

    // Procedural widget list building
    final List<pw.Widget> buildList = [];

    // 1. Header
    buildList.add(_buildPremiumHeader(
      testTitle,
      score,
      totalMarks,
      correctAnswers,
      wrongAnswers,
      skippedAnswers,
      primaryFont,
      fallbackFont,
    ));

    // 2. Detailed Analysis Title
    if (questions != null && questions.isNotEmpty) {
      buildList.add(pw.SizedBox(height: 15));
      buildList.add(
        pw.Text(
          'Detailed Analysis',
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.black,
            font: primaryFont,
            fontFallback: [fallbackFont],
          ),
        ),
      );
      buildList.add(pw.SizedBox(height: 8));

      // 3. Question Widgets (Exploded list for zero-gap pagination)
      for (var i = 0; i < questions.length; i++) {
        final q = questions[i];
        final selectedIdx = selectedAnswers?[i];
        buildList.addAll(_buildAnalysisWidgetList(
          i + 1,
          q,
          selectedIdx,
          primaryFont,
          fallbackFont,
        ));
      }
    }

    // 4. Final Footer
    buildList.add(pw.SizedBox(height: 20));
    buildList.add(
      pw.Center(
        child: pw.Text(
          'Generated by Krushi Kalp App',
          style: pw.TextStyle(
            color: PdfColors.grey500,
            fontSize: 10,
            font: primaryFont,
            fontFallback: [fallbackFont],
          ),
        ),
      ),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(35),
        theme: pw.ThemeData.withFont(
          base: primaryFont,
          bold: primaryFont,
          italic: primaryFont,
        ).copyWith(
          defaultTextStyle: pw.TextStyle(
            font: primaryFont,
            fontFallback: [fallbackFont],
          ),
        ),
        footer: (pw.Context context) => pw.Container(
          height: 30,
          width: double.infinity,
          alignment: pw.Alignment.bottomRight,
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(
              color: PdfColors.grey500,
              fontSize: 9,
              font: primaryFont,
              fontFallback: [fallbackFont],
            ),
          ),
        ),
        build: (pw.Context context) => buildList,
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File("${dir.path}/result_$testId.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  pw.Widget _buildPremiumHeader(
    String title,
    double score,
    double totalMarks,
    int correct,
    int wrong,
    int skipped,
    pw.Font primaryFont,
    pw.Font fallbackFont,
  ) {
    final double percentage = (score / totalMarks) * 100;
    final bool isPassed = percentage >= 35;
    final PdfColor brandBlue = PdfColor.fromInt(0xFF3399FF);
    final PdfColor statRed = PdfColor.fromInt(0xFFF44336);

    return pw.Column(
      children: [
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.symmetric(vertical: 5),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('KRUSHI KALP',
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 8,
                      color: PdfColors.grey600,
                      font: primaryFont,
                      fontFallback: [fallbackFont])),
              pw.Text(
                  '${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                  style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600,
                      font: primaryFont,
                      fontFallback: [fallbackFont])),
            ],
          ),
        ),
        pw.Container(
          width: double.infinity,
          margin: const pw.EdgeInsets.symmetric(vertical: 10),
          padding: const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 15),
          decoration: pw.BoxDecoration(
            color: brandBlue,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('REPORT SUMMARY',
                      style: pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 8,
                          fontWeight: pw.FontWeight.bold,
                          font: primaryFont,
                          fontFallback: [fallbackFont])),
                  pw.SizedBox(height: 2),
                  pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('${percentage.toStringAsFixed(1)}%',
                          style: pw.TextStyle(
                              fontSize: 26,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.white,
                              font: primaryFont,
                              fontFallback: [fallbackFont])),
                      pw.SizedBox(width: 5),
                      pw.Text('PASS SCORE',
                          style: pw.TextStyle(
                              color: PdfColors.white.withAlpha(0.7),
                              fontSize: 8,
                              font: primaryFont,
                              fontFallback: [fallbackFont])),
                    ],
                  ),
                ],
              ),
              pw.Text(isPassed ? 'PASSED' : 'FAILED',
                  style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      font: primaryFont,
                      fontFallback: [fallbackFont])),
            ],
          ),
        ),
        pw.Row(
          children: [
            pw.Expanded(
              child:
                  _buildStatCard('CORRECT', '$correct', brandBlue, primaryFont, fallbackFont),
            ),
            pw.SizedBox(width: 8),
            pw.Expanded(
              child: _buildStatCard('WRONG', '$wrong', statRed, primaryFont, fallbackFont),
            ),
            pw.SizedBox(width: 8),
            pw.Expanded(
              child: _buildStatCard(
                  'SKIPPED', '$skipped', PdfColors.grey700, primaryFont, fallbackFont),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildStatCard(
      String label, String value, PdfColor color, pw.Font font, pw.Font fallback) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border.all(color: PdfColors.grey200),
      ),
      child: pw.Column(
        children: [
          pw.Text(label,
              style: pw.TextStyle(
                  fontSize: 7,
                  color: PdfColors.grey600,
                  font: font,
                  fontFallback: [fallback])),
          pw.SizedBox(height: 2),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  color: color,
                  font: font,
                  fontFallback: [fallback])),
        ],
      ),
    );
  }

  List<pw.Widget> _buildAnalysisWidgetList(
    int number,
    Question q,
    int? selectedIdx,
    pw.Font primaryFont,
    pw.Font fallbackFont,
  ) {
    final PdfColor correctGreen = PdfColor.fromInt(0xFF4CAF50);
    final PdfColor errorRed = PdfColor.fromInt(0xFFF44336);
    final isSkipped = selectedIdx == null;

    PdfColor statusColor = PdfColors.grey400;
    if (!isSkipped) {
      final isCorrect = q.options[selectedIdx].trim().toLowerCase() ==
          q.correctAnswer.trim().toLowerCase();
      statusColor = isCorrect ? correctGreen : errorRed;
    }

    final List<pw.Widget> widgets = [];

    // Helper to build a "Fake" table row as an independent widget
    pw.Widget buildFlatRow({
      required pw.Widget child,
      PdfColor? bgColor,
      double? height,
      bool hasBottomBorder = false,
      PdfColor? accentColor,
    }) {
      return pw.Container(
        decoration: pw.BoxDecoration(
          color: bgColor ?? PdfColors.white,
          border: pw.Border(
            left: pw.BorderSide(
              color: accentColor ?? statusColor.withAlpha(0.1),
              width: 4,
            ),
            bottom: hasBottomBorder
                ? const pw.BorderSide(color: PdfColors.grey200, width: 0.5)
                : pw.BorderSide.none,
          ),
        ),
        padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
        child: child,
      );
    }

    // 1. Question Header
    widgets.add(buildFlatRow(
      accentColor: statusColor,
      child: pw.Row(
        children: [
          pw.Text('Question #$number',
              style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 10,
                  font: primaryFont,
                  fontFallback: [fallbackFont])),
          pw.SizedBox(width: 10),
          pw.Text('Difficulty: Standard',
              style: pw.TextStyle(
                  color: PdfColors.grey500,
                  fontSize: 8,
                  font: primaryFont,
                  fontFallback: [fallbackFont])),
        ],
      ),
    ));

    // 2. Question Text
    widgets.add(buildFlatRow(
      child: pw.Text(
        q.text,
        style: pw.TextStyle(
          fontSize: 11,
          fontWeight: pw.FontWeight.bold,
          font: primaryFont,
          fontFallback: [fallbackFont],
        ),
      ),
    ));

    // 3. Options
    for (var optIndex = 0; optIndex < q.options.length; optIndex++) {
      final isSelected = selectedIdx == optIndex;
      final isRealAnswer = q.options[optIndex].trim().toLowerCase() ==
          q.correctAnswer.trim().toLowerCase();

      PdfColor rowColor = PdfColors.white;
      if (isRealAnswer) {
        rowColor = PdfColor.fromInt(0xFFE8F5E9);
      } else if (isSelected && !isRealAnswer) {
        rowColor = PdfColor.fromInt(0xFFFFEBEE);
      }

      widgets.add(buildFlatRow(
        bgColor: rowColor,
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Expanded(
              child: pw.Text(
                q.options[optIndex],
                style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: (isSelected || isRealAnswer) ? pw.FontWeight.bold : pw.FontWeight.normal,
                  font: primaryFont,
                  fontFallback: [fallbackFont],
                ),
              ),
            ),
            if (isRealAnswer || (isSelected && !isRealAnswer))
              _buildSelectionIndicator(isRealAnswer, correctGreen, errorRed),
          ],
        ),
      ));
    }

    // 4. Spacer/Divider
    widgets.add(buildFlatRow(
      hasBottomBorder: true,
      child: pw.SizedBox(height: 4),
    ));

    return widgets;
  }

  pw.Widget _buildSelectionIndicator(bool isCorrect, PdfColor darkG, PdfColor darkR) {
    return pw.Container(
      width: 14,
      height: 14,
      decoration: pw.BoxDecoration(
        color: isCorrect ? darkG : darkR,
        shape: pw.BoxShape.circle,
      ),
      child: pw.Center(
        child: pw.Container(
          width: 8,
          height: 8,
          child: pw.CustomPaint(
            painter: (PdfGraphics canvas, PdfPoint size) {
              canvas.setStrokeColor(PdfColors.white);
              canvas.setLineWidth(1.5);
              if (isCorrect) {
                canvas.moveTo(1, 4);
                canvas.lineTo(3, 6);
                canvas.lineTo(7, 1.5);
              } else {
                canvas.moveTo(2, 2);
                canvas.lineTo(6, 6);
                canvas.moveTo(2, 6);
                canvas.lineTo(6, 2);
              }
              canvas.strokePath();
            },
          ),
        ),
      ),
    );
  }

  /// Loads the required font strictly, falling back to Unicode-ready assets.
  Future<pw.Font> _loadFont(String languageCode,
      {bool forceGujarati = false}) async {
    // ALWAYS try asset first as it is the only way to avoid Unicode 'Idiot Space' height errors
    try {
      final fontData = await rootBundle.load("assets/fonts/NotoSansGujarati-Regular.ttf");
      return pw.Font.ttf(fontData);
    } catch (e) {
      // If asset fails, use Helvetica ONLY for English, but warning: height may vary
      if (languageCode == 'en' && !forceGujarati) {
        return pw.Font.helvetica();
      }
    }

    try {
      final dir = await getApplicationDocumentsDirectory();
      final file = File("${dir.path}/NotoSansGujarati.ttf");
      if (await file.exists()) {
        return pw.Font.ttf(await file.readAsBytes().then((b) => b.buffer.asByteData()));
      }
      
      // Attempt download as last resort
      final url = Uri.parse("https://cdn.jsdelivr.net/npm/@expo-google-fonts/noto-sans-gujarati@0.2.3/NotoSansGujarati_400Regular.ttf");
      final client = HttpClient()..badCertificateCallback = (cert, host, port) => true;
      final request = await client.getUrl(url);
      final response = await request.close();
      if (response.statusCode == 200) {
        final bytes = await condenseStream(response);
        await file.writeAsBytes(bytes);
        return pw.Font.ttf(bytes.buffer.asByteData());
      }
    } catch (_) {}
    
    return pw.Font.helvetica();
  }

  Future<Uint8List> condenseStream(Stream<List<int>> stream) async {
    final List<int> allBytes = [];
    await for (final List<int> chunk in stream) {
      allBytes.addAll(chunk);
    }
    return Uint8List.fromList(allBytes);
  }

  String getSecurePassword(String userId, String testTitle) {
    return "${userId.substring(0, 4)}@${testTitle.length}";
  }
}
